# Generated by Django 4.1 on 2022-08-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenthousing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='republic',
            name='house_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
