# Generated by Django 4.1 on 2022-08-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studenthousing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='republic',
            old_name='republic',
            new_name='user',
        ),
    ]
