# Generated by Django 4.1 on 2022-08-17 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studenthousing', '0002_rename_republic_republic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='republic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='republics', to='studenthousing.user'),
        ),
    ]
