# Generated by Django 4.1 on 2022-08-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenthousing', '0006_alter_locator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locator',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
